# Generated by Django 4.2.6 on 2024-08-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='DirectivePrincipleofOurStatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentalRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='humanRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='LegalRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='politicalRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('Images', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
    ]
