# Generated by Django 4.2.6 on 2024-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_remove_civilrights_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='civilrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='civilrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='civilrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='directiveprincipleofourstatepolicy',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='directiveprincipleofourstatepolicy',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='directiveprincipleofourstatepolicy',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='directiveprincipleofourstatepolicy',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='economicrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='economicrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='economicrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='economicrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='environmentalrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='environmentalrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='environmentalrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='environmentalrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fundamentalrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fundamentalrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fundamentalrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='humanrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='humanrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='humanrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='humanrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legalrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='legalrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='legalrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='legalrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='politicalrights',
            name='ex1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='politicalrights',
            name='ex2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='politicalrights',
            name='img1',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='politicalrights',
            name='img2',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
