# Generated by Django 4.2.6 on 2024-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_civilrights_ex1_civilrights_ex2_civilrights_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
