# Generated by Django 4.2.6 on 2024-10-13 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rights', '0005_remove_lawyer_email_lawyer_doc_lawyer_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
