# Generated by Django 4.2.6 on 2024-10-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0006_lawyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='user',
        ),
    ]
