# Generated by Django 4.2.6 on 2025-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0008_criminallaw_personallaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
