# Generated by Django 4.2.6 on 2025-03-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0010_comment_lawyer_user_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rights.lawyer'),
        ),
    ]
