# Generated by Django 4.2.6 on 2025-03-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0012_theunionanditsterritory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheUnionandItsTerritory',
            new_name='UnionTerritory',
        ),
    ]
