# Generated by Django 4.2.6 on 2025-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0013_rename_theunionanditsterritory_unionterritory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
