# Generated by Django 4.2.6 on 2025-03-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0016_case_remove_reply_comment_remove_reply_lawyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='associated_lawyers',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='supervising_lawyer',
        ),
    ]
