# Generated by Django 4.2.6 on 2025-03-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0018_lawyer_associated_lawyers_lawyer_supervising_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='associated_lawyers',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='supervising_lawyer',
        ),
        migrations.DeleteModel(
            name='case',
        ),
    ]
