# Generated by Django 4.2.6 on 2025-03-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0019_remove_lawyer_associated_lawyers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='associated_lawyers',
            field=models.ManyToManyField(blank=True, related_name='associated_with', to='rights.lawyer'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='supervising_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='rights.lawyer'),
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200)),
                ('completion', models.FloatField(default=0.0)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cases', to='rights.lawyer')),
            ],
        ),
    ]
