# Generated by Django 4.2.6 on 2025-03-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0022_alter_case_client_alter_case_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='user',
        ),
    ]
