# Generated by Django 4.2.6 on 2025-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0023_remove_lawyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='supervising_lawyer',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='supervising_lawyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='subordinates', to='rights.lawyer'),
        ),
    ]
