# Generated by Django 4.2.6 on 2025-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0024_remove_lawyer_supervising_lawyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='supervising_lawyer',
            field=models.ManyToManyField(blank=True, to='rights.lawyer'),
        ),
    ]
