# Generated by Django 4.2.6 on 2025-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0025_alter_lawyer_supervising_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='supervising_lawyer',
            field=models.ManyToManyField(blank=True, related_name='subordinates', to='rights.lawyer'),
        ),
    ]
