# Generated by Django 4.2.6 on 2025-04-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0026_alter_lawyer_supervising_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='rights.client'),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='rights.lawyer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='supervising_lawyer',
            field=models.ManyToManyField(blank=True, related_name='supervised_by', to='rights.lawyer'),
        ),
    ]
