# Generated by Django 4.2.6 on 2025-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0027_remove_client_user_alter_case_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='associated_lawyers',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='supervising_lawyer',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='associated_lawyers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='supervising_lawyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
